const User = require("../models/user.Schema");
const jwt = require("jsonwebtoken");

const createToken = (_id) => {
  return jwt.sign({ _id }, process.env.SECRET, { expiresIn: "3d" });
};

const login = async (req, res) => {
  const { email, password } = req.body;

  try {
    const user = await User.login(email, password);

    const autoGeneratedUsername = email.split("@")[0];

    const token = createToken(user._id);
    res.status(200).json({ autoGeneratedUsername, token });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
};

const signup = async (req, res) => {
  const { email, password } = req.body;

  try {
    const user = await User.signup(email, password);

    const autoGeneratedUsername = email.split("@")[0];

    const token = createToken(user._id);
    res.status(201).json({ autoGeneratedUsername, token });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
};

module.exports = { login, signup };
